# Generated by Django 5.0.3 on 2024-03-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_banner_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizeprice',
            name='size',
        ),
        migrations.AddField(
            model_name='productsizeprice',
            name='size_ru',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Размер (ru)'),
        ),
        migrations.AddField(
            model_name='productsizeprice',
            name='size_tm',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Размер (tm)'),
        ),
    ]
