# Generated by Django 5.0.3 on 2024-03-13 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_orderitem', to='product.order', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
