# Generated by Django 5.0.3 on 2024-03-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productsizeprice_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_cheap',
            field=models.BooleanField(default=False, verbose_name='Дешевый?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новый?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Специальный?'),
        ),
    ]
