# Generated by Django 5.0.3 on 2024-03-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_relatedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='amount_min',
            field=models.IntegerField(default=0, verbose_name='Мин на бесплатную доставку'),
        ),
        migrations.AddField(
            model_name='settings',
            name='ref_add_point',
            field=models.IntegerField(default=5, verbose_name='балл для реферала'),
        ),
    ]
