# Generated by Django 5.0.3 on 2024-03-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_settings_amount_min_settings_ref_add_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='nr_content_ru',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='nr_content_tm',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='nr_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Фото для 1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='nr_title_ru',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='nr_title_tm',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='r_content_ru',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='r_content_tm',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='r_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Фото для 1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='r_title_ru',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='r_title_tm',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
